sudo: required
language: erlang
otp_release: 18.2.1
services:
  - docker
  - git

script:
  - gradle clean
  - gradle wrapper
  - docker build -t message-broker:1.0 ./build

after_success:
- sh ./deploy/docker_pusher.sh